booking.property = Booking Profile Prod

#Configuracion de la base de datos
spring.datasource.url = jdbc:mysql://localhost:3306/bookingdb
spring.datasource.username = root
spring.datasource.password = Yamileth120195